name: chocolatine

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-safia.beaumale-mesmar"
  EXECUTABLES: "binary"
  ARGUMENTS: ""

jobs:
  coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Check project coding style !"
        run:
          run: |
            check.sh $(pwd) $(pwd) # Exécute le script "check.sh" avec l'emplacement actuel du projet comme argument.

            if [[ -s coding-style-reports.log && $(grep -c 'Error' coding-style-reports.log) -gt 0 ]]; then # Vérifie si le fichier de rapport de style de code n'est pas vide et contient au moins une erreur.
              exit 1; # Si le fichier n'est pas vide et contient une erreur, le script échoue avec un code de sortie de 1.
            else
              exit 0; # Sinon, le script réussit avec un code de sortie de 0.
            fi;
  
            echo "::set-output name=number_of_errors::$(grep -c 'Error' coding-style-reports.log)" # Définit la variable de sortie "number_of_errors" avec le nombre d'erreurs trouvées dans le fichier de rapport de style de code à l'aide de la commande "grep".


  compilation:
    name: "Checks compilation of binaries given !"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    needs: 
      - coding_style

    steps:
      - uses: actions/checkout@v3
      - run: make
        timeout-minutes: 2
      - run: make clean
      - run: |
          OIFS=$IFS
          IFS=','
          for x in $EXECUTABLES
            do
              ./$x
            done
          IFS=$OIFS

  run_tests:
    name: "Runs criterion tests !"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    needs: 
      - compilation

    steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    name: "Push files to given mirror repo !"
    runs-on: ubuntu-latest
    needs:
      - run_tests

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@main
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_KEY }}
